version: '3'

services:
    nginx:
        container_name: nginx-container
        build:
            context: ./docker
            dockerfile: nginx.docker
        volumes:
            - ./:/app
            - ./var/log/nginx:/var/log/nginx:cached
        depends_on:
            - php-fpm
            - mailer
        ports:
            - "8080:80"
            - "8090:443"
    nginx-frontend:
        container_name: nginx-frontend-container
        build:
            context: ./docker/frontend/
            dockerfile: nginx.docker
        volumes:
            - ./client:/app
            - ./var/frontend-log/nginx:/var/log/nginx:cached
        depends_on:
            - node
        ports:
            - "4000:80"
            - "4001:443"
    php-fpm:
        container_name: php-fpm-container
        build:
            context: ./docker
            dockerfile: php-fpm.docker
        volumes:
            - ./:/app
            - composer:/root/.composer/cache
            - ./docker/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        depends_on:
            - mysql
            - mailer
        environment:
            XDEBUG_CONFIG: "remote_host=172.17.0.1 remote_enable=1"
            PHP_IDE_CONFIG: "serverName=docker"
            # for macOS IP 10.254.254.254
    node:
        build:
            context: ./docker/frontend
            dockerfile: node.docker
        volumes:
            - ./:/app
        working_dir: /app
        tty: true
        ports:
            - "3000:3000"
    mysql:
        container_name: mysql-container
        image: mysql:5.7
        ports:
            - "3306:3306"
        volumes:
            - ./.data/db:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=laravel
        restart: always
        command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin-container
        depends_on:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        ports:
            - '8081:80'
        volumes:
            - /sessions
    mailer:
        image: mailhog/mailhog
        ports:
            - "8082:8025"

volumes:
    mysql:
    composer:
